/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Balance_general extends javax.swing.JFrame {

    /**
     * Creates new form Balance_general
     */
    
    DefaultTableModel mt = new DefaultTableModel();
    
    public Balance_general() {
        initComponents();
        setLocationRelativeTo(null); 
        
        String Titulocolumnas [] = {"Codigo", "Activos","1","2","3","4"};
        
        mt.setColumnIdentifiers(Titulocolumnas);
        
        Tabla1.setModel(mt);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FONDOO = new javax.swing.JPanel();
        LlenardatosTXT = new javax.swing.JLabel();
        NombredelaEmpresaTXT = new javax.swing.JLabel();
        FECHATXT = new javax.swing.JLabel();
        BALANCEGENERALTXT = new javax.swing.JLabel();
        BTActualizardatos = new javax.swing.JButton();
        BTBorrarFila = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PanelNombreYfecha = new javax.swing.JPanel();
        NombreEmpresatxt = new javax.swing.JLabel();
        NombreEmpresaINPUT = new javax.swing.JTextField();
        Fechatxt = new javax.swing.JLabel();
        FechaINPUT = new javax.swing.JTextField();
        PanelCuentasActivos = new javax.swing.JPanel();
        CuentasActivosTXT = new javax.swing.JLabel();
        NombredelacuentaTXT = new javax.swing.JLabel();
        NombresActivosInput = new javax.swing.JTextField();
        VALORTXT = new javax.swing.JLabel();
        ValoresActivosInput = new javax.swing.JTextField();
        CodigoTXT = new javax.swing.JLabel();
        BTañadircuentasactivos = new javax.swing.JButton();
        CodigoActivosInput = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 700));

        FONDOO.setBackground(new java.awt.Color(255, 255, 255));
        FONDOO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LlenardatosTXT.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        LlenardatosTXT.setText("LLENAR DATOS");
        FONDOO.add(LlenardatosTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, -1));

        NombredelaEmpresaTXT.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        NombredelaEmpresaTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombredelaEmpresaTXT.setText("LA COMERCIAL SA");
        NombredelaEmpresaTXT.setToolTipText("");
        NombredelaEmpresaTXT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FONDOO.add(NombredelaEmpresaTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 740, -1));

        FECHATXT.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        FECHATXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FECHATXT.setText("BALANCE GENERAL DE LA EMPRESA XD, DE FECHA TAL");
        FECHATXT.setToolTipText("");
        FECHATXT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FONDOO.add(FECHATXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 740, 20));

        BALANCEGENERALTXT.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BALANCEGENERALTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BALANCEGENERALTXT.setText("BALANCE GENERAL");
        BALANCEGENERALTXT.setToolTipText("");
        BALANCEGENERALTXT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BALANCEGENERALTXT.setName("BALANCE GENERAL"); // NOI18N
        FONDOO.add(BALANCEGENERALTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 740, -1));

        BTActualizardatos.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        BTActualizardatos.setText("ACTUALIZAR DATOS");
        BTActualizardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTActualizardatosActionPerformed(evt);
            }
        });
        FONDOO.add(BTActualizardatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, 200, -1));

        BTBorrarFila.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        BTBorrarFila.setText("BORRAR FILA");
        BTBorrarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBorrarFilaActionPerformed(evt);
            }
        });
        FONDOO.add(BTBorrarFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 560, 200, -1));

        jButton1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        FONDOO.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 200, 20));

        NombreEmpresatxt.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        NombreEmpresatxt.setText("Nombre de la empresa");

        Fechatxt.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        Fechatxt.setText("Fecha del balance general");

        FechaINPUT.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N

        javax.swing.GroupLayout PanelNombreYfechaLayout = new javax.swing.GroupLayout(PanelNombreYfecha);
        PanelNombreYfecha.setLayout(PanelNombreYfechaLayout);
        PanelNombreYfechaLayout.setHorizontalGroup(
            PanelNombreYfechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombreYfechaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelNombreYfechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Fechatxt)
                    .addComponent(NombreEmpresatxt)
                    .addComponent(NombreEmpresaINPUT)
                    .addComponent(FechaINPUT, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        PanelNombreYfechaLayout.setVerticalGroup(
            PanelNombreYfechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombreYfechaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(NombreEmpresatxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreEmpresaINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fechatxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FechaINPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        FONDOO.add(PanelNombreYfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 310, 130));

        CuentasActivosTXT.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CuentasActivosTXT.setText("CUENTAS DE ACTIVOS");

        NombredelacuentaTXT.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        NombredelacuentaTXT.setText("Nombre de la cuenta ");

        VALORTXT.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        VALORTXT.setText("Valor");

        CodigoTXT.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        CodigoTXT.setText("Codigo de la cuenta");

        BTañadircuentasactivos.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BTañadircuentasactivos.setText("Añadir");
        BTañadircuentasactivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTañadircuentasactivosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCuentasActivosLayout = new javax.swing.GroupLayout(PanelCuentasActivos);
        PanelCuentasActivos.setLayout(PanelCuentasActivosLayout);
        PanelCuentasActivosLayout.setHorizontalGroup(
            PanelCuentasActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCuentasActivosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelCuentasActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CodigoTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ValoresActivosInput)
                    .addComponent(VALORTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombresActivosInput)
                    .addComponent(NombredelacuentaTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CuentasActivosTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(CodigoActivosInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(BTañadircuentasactivos)
                .addGap(23, 23, 23))
        );
        PanelCuentasActivosLayout.setVerticalGroup(
            PanelCuentasActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCuentasActivosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(CuentasActivosTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NombredelacuentaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCuentasActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCuentasActivosLayout.createSequentialGroup()
                        .addComponent(NombresActivosInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VALORTXT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ValoresActivosInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(CodigoTXT))
                    .addComponent(BTañadircuentasactivos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CodigoActivosInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        FONDOO.add(PanelCuentasActivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 310, 240));

        Tabla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tabla1);

        FONDOO.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 740, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FONDOO, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FONDOO, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static int contador = -1;
    public static Double TotalActivos = 0.0;
    public static String NombresActivos;
    public static Double ValorActivos = 0.0;
    public static int CodigoActivos = 0;
     
    private void BTañadircuentasactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTañadircuentasactivosActionPerformed
       NombresActivos = String.valueOf(NombresActivosInput.getText());
       ValorActivos = Double.valueOf(ValoresActivosInput.getText());
       CodigoActivos = Integer.parseInt(CodigoActivosInput.getText());
       
               
       mt.addRow(new Object[]{CodigoActivos,NombresActivos,"",ValorActivos,""});
       contador++;
       TotalActivos += ValorActivos;
       
       NombresActivosInput.setText("");
       ValoresActivosInput.setText("");
       CodigoActivosInput.setText("");
    }//GEN-LAST:event_BTañadircuentasactivosActionPerformed

    private void BTActualizardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTActualizardatosActionPerformed

        NombredelaEmpresaTXT.setText(NombreEmpresaINPUT.getText());
        FECHATXT.setText(FechaINPUT.getText());
        
        mt.addRow(new Object[]{"","","","",""});
        
        mt.setValueAt(TotalActivos, contador +1 , 4);
        mt.setValueAt("TOTAL ACTIVOS", contador +1 , 0);
    }//GEN-LAST:event_BTActualizardatosActionPerformed

    private void BTBorrarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBorrarFilaActionPerformed
       mt.removeRow(Tabla1.getSelectedRow());
    }//GEN-LAST:event_BTBorrarFilaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mt.setValueAt(CodigoActivosInput.getText(), Tabla1.getSelectedRow(), 0);
        mt.setValueAt(NombresActivosInput.getText(), Tabla1.getSelectedRow(), 1);
        mt.setValueAt(ValoresActivosInput.getText(), Tabla1.getSelectedRow(), 3);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Balance_general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Balance_general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Balance_general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Balance_general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Balance_general().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BALANCEGENERALTXT;
    private javax.swing.JButton BTActualizardatos;
    private javax.swing.JButton BTBorrarFila;
    private javax.swing.JButton BTañadircuentasactivos;
    private javax.swing.JTextField CodigoActivosInput;
    private javax.swing.JLabel CodigoTXT;
    private javax.swing.JLabel CuentasActivosTXT;
    private javax.swing.JLabel FECHATXT;
    private javax.swing.JPanel FONDOO;
    private javax.swing.JTextField FechaINPUT;
    private javax.swing.JLabel Fechatxt;
    private javax.swing.JLabel LlenardatosTXT;
    private javax.swing.JTextField NombreEmpresaINPUT;
    private javax.swing.JLabel NombreEmpresatxt;
    private javax.swing.JLabel NombredelaEmpresaTXT;
    private javax.swing.JLabel NombredelacuentaTXT;
    private javax.swing.JTextField NombresActivosInput;
    private javax.swing.JPanel PanelCuentasActivos;
    private javax.swing.JPanel PanelNombreYfecha;
    private javax.swing.JTable Tabla1;
    private javax.swing.JLabel VALORTXT;
    private javax.swing.JTextField ValoresActivosInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
