
package com.login;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *author: Hermant Diaz.
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    
    public Login() {
        initComponents();
        setLocationRelativeTo(null);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        image1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        iniciarsesionTXT = new javax.swing.JLabel();
        usuariotxt = new javax.swing.JLabel();
        usuarioinput = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Contraseñatxt = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        contraseñainput = new javax.swing.JPasswordField();
        ENTRAR = new javax.swing.JPanel();
        ENTRARTXT = new javax.swing.JLabel();
        CREARUSUARIO = new javax.swing.JPanel();
        CrearUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));

        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen2(1).png"))); // NOI18N
        image1.setText("jLabel1");

        logo.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO.png"))); // NOI18N
        logo.setText("CONTABILIDAD FINANCIERA");

        iniciarsesionTXT.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        iniciarsesionTXT.setText("INICIAR SESIÓN");

        usuariotxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        usuariotxt.setText("USUARIO");

        usuarioinput.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        usuarioinput.setForeground(new java.awt.Color(204, 204, 204));
        usuarioinput.setText("Ingrese su nombre de usuario");
        usuarioinput.setBorder(null);
        usuarioinput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioinputMousePressed(evt);
            }
        });
        usuarioinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioinputActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        Contraseñatxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Contraseñatxt.setText("CONTRASEÑA");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        contraseñainput.setForeground(new java.awt.Color(204, 204, 204));
        contraseñainput.setText("********");
        contraseñainput.setBorder(null);
        contraseñainput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contraseñainputMousePressed(evt);
            }
        });

        ENTRAR.setBackground(new java.awt.Color(255, 111, 157));
        ENTRAR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ENTRARTXT.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        ENTRARTXT.setForeground(new java.awt.Color(255, 255, 255));
        ENTRARTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ENTRARTXT.setText("ENTRAR");
        ENTRARTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ENTRARTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ENTRARTXTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ENTRARLayout = new javax.swing.GroupLayout(ENTRAR);
        ENTRAR.setLayout(ENTRARLayout);
        ENTRARLayout.setHorizontalGroup(
            ENTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ENTRARTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );
        ENTRARLayout.setVerticalGroup(
            ENTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ENTRARTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        CREARUSUARIO.setBackground(new java.awt.Color(255, 255, 255));

        CrearUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CrearUsuario.setForeground(new java.awt.Color(255, 111, 157));
        CrearUsuario.setText("¿No tiene un usuario? Clickee aquí para crearlo");
        CrearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CREARUSUARIOLayout = new javax.swing.GroupLayout(CREARUSUARIO);
        CREARUSUARIO.setLayout(CREARUSUARIOLayout);
        CREARUSUARIOLayout.setHorizontalGroup(
            CREARUSUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CREARUSUARIOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CREARUSUARIOLayout.setVerticalGroup(
            CREARUSUARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CREARUSUARIOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CrearUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(usuarioinput)
                            .addComponent(jSeparator1)
                            .addComponent(contraseñainput)
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addComponent(ENTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                                .addComponent(CREARUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Contraseñatxt)
                                    .addComponent(usuariotxt)
                                    .addComponent(iniciarsesionTXT))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(logo)
                .addGap(45, 45, 45)
                .addComponent(iniciarsesionTXT)
                .addGap(36, 36, 36)
                .addComponent(usuariotxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuarioinput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Contraseñatxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contraseñainput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ENTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CREARUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioinputActionPerformed

    private void usuarioinputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioinputMousePressed
        // TODO add your handling code here:
        if (usuarioinput.getText().equals("Ingrese su nombre de usuario")){
         usuarioinput.setText("");
         usuarioinput.setForeground(Color.black);
        }
       
        if(String.valueOf(contraseñainput.getPassword()).isEmpty()){
        contraseñainput.setText("********");
        contraseñainput.setForeground(Color.gray);
        }
       
        
    }//GEN-LAST:event_usuarioinputMousePressed

    private void contraseñainputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñainputMousePressed
        // TODO add your handling code here:
                // TODO add your handling code here:

        if(String.valueOf(contraseñainput.getPassword()).equals("********")){
        contraseñainput.setText("");
        contraseñainput.setForeground(Color.black);
        }
        
        if(usuarioinput.getText().isEmpty()){
        usuarioinput.setText("Ingrese su nombre de usuario");
        usuarioinput.setForeground(Color.gray);
        }

     
    }//GEN-LAST:event_contraseñainputMousePressed

    private void CrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUsuarioMouseClicked
        Registrarse MostrarR = new Registrarse();
        MostrarR = new Registrarse();
        MostrarR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CrearUsuarioMouseClicked


    private void ENTRARTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENTRARTXTMouseClicked
      Registrarse datos = new Registrarse();

      String usuario = datos.NuevoUsuario;
      String contraseña = datos.NuevaContraseña;
      
      String U = new String (usuarioinput.getText());
      String C = new String (contraseñainput.getText());
     
      
      //ingresar a otra pagina
      if (U.equals(usuario) && C.equals(contraseña)){
          Menu mostrarMenu = new Menu();
          mostrarMenu.mostrarusuario(usuario);
          mostrarMenu.setVisible(true);
          this.dispose();
      }
      else {
          JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecto");
      }
    }//GEN-LAST:event_ENTRARTXTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CREARUSUARIO;
    private javax.swing.JLabel Contraseñatxt;
    private javax.swing.JLabel CrearUsuario;
    private javax.swing.JPanel ENTRAR;
    private javax.swing.JLabel ENTRARTXT;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPasswordField contraseñainput;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel iniciarsesionTXT;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField usuarioinput;
    private javax.swing.JLabel usuariotxt;
    // End of variables declaration//GEN-END:variables
}
