/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;
import java.awt.Color;
/**
 *
 * @Hermant Diaz
 */
public class Menu extends javax.swing.JFrame {
    private String mostrarusuario;

    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null); 
    }

    public void mostrarusuario( String mostrarusuario ){
        this.mostrarusuario = mostrarusuario;
        usuarioTXT.setText(mostrarusuario);
    }
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        logo2 = new javax.swing.JLabel();
        preguntaTXT = new javax.swing.JLabel();
        bienvenidoTXT = new javax.swing.JLabel();
        usuarioTXT = new javax.swing.JLabel();
        BotonOpcion1 = new javax.swing.JButton();
        BotonOpcion2 = new javax.swing.JButton();
        BotonOpcion3 = new javax.swing.JButton();
        BotonOpcion4 = new javax.swing.JButton();
        BotonOpcion5 = new javax.swing.JButton();
        BotonOpcion6 = new javax.swing.JButton();
        imagemenu1 = new javax.swing.JLabel();
        imagemenu2 = new javax.swing.JLabel();
        imagemenu3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(982, 500));
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setPreferredSize(new java.awt.Dimension(982, 500));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo2.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGO.png"))); // NOI18N
        logo2.setText("CONTABILIDAD FINANCIERA");
        fondo.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 31, -1, -1));

        preguntaTXT.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        preguntaTXT.setText("¿Qué quieres hacer?");
        fondo.add(preguntaTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 160, -1, -1));

        bienvenidoTXT.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        bienvenidoTXT.setText("Bienvenido,");
        fondo.add(bienvenidoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 109, -1, -1));

        usuarioTXT.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        usuarioTXT.setText(",");
        usuarioTXT.setToolTipText("");
        fondo.add(usuarioTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 109, 200, -1));

        BotonOpcion1.setBackground(new java.awt.Color(255, 111, 157));
        BotonOpcion1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BotonOpcion1.setForeground(new java.awt.Color(255, 255, 255));
        BotonOpcion1.setText("OPCION1");
        BotonOpcion1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 111, 157), 3));
        BotonOpcion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOpcion1ActionPerformed(evt);
            }
        });
        fondo.add(BotonOpcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 390, 50));

        BotonOpcion2.setBackground(new java.awt.Color(255, 111, 157));
        BotonOpcion2.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BotonOpcion2.setForeground(new java.awt.Color(255, 255, 255));
        BotonOpcion2.setText("OPCION2");
        BotonOpcion2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 111, 157), 3));
        BotonOpcion2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOpcion2ActionPerformed(evt);
            }
        });
        fondo.add(BotonOpcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 390, 50));

        BotonOpcion3.setBackground(new java.awt.Color(255, 111, 157));
        BotonOpcion3.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BotonOpcion3.setForeground(new java.awt.Color(255, 255, 255));
        BotonOpcion3.setText("OPCION3");
        BotonOpcion3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 111, 157), 3));
        BotonOpcion3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOpcion3ActionPerformed(evt);
            }
        });
        fondo.add(BotonOpcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 390, 50));

        BotonOpcion4.setBackground(new java.awt.Color(255, 111, 157));
        BotonOpcion4.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BotonOpcion4.setForeground(new java.awt.Color(255, 255, 255));
        BotonOpcion4.setText("OPCION4");
        BotonOpcion4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 111, 157), 3));
        BotonOpcion4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOpcion4ActionPerformed(evt);
            }
        });
        fondo.add(BotonOpcion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 370, 50));

        BotonOpcion5.setBackground(new java.awt.Color(255, 111, 157));
        BotonOpcion5.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BotonOpcion5.setForeground(new java.awt.Color(255, 255, 255));
        BotonOpcion5.setText("OPCION5");
        BotonOpcion5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 111, 157), 3));
        BotonOpcion5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonOpcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOpcion5ActionPerformed(evt);
            }
        });
        fondo.add(BotonOpcion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 370, 50));

        BotonOpcion6.setBackground(new java.awt.Color(255, 111, 157));
        BotonOpcion6.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BotonOpcion6.setForeground(new java.awt.Color(255, 255, 255));
        BotonOpcion6.setText("OPCION6");
        BotonOpcion6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 111, 157), 3));
        BotonOpcion6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonOpcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOpcion6ActionPerformed(evt);
            }
        });
        fondo.add(BotonOpcion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 370, 50));

        imagemenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagenmenu(3).png"))); // NOI18N
        fondo.add(imagemenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 320, 210));

        imagemenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagenmenu(1).png"))); // NOI18N
        imagemenu2.setOpaque(true);
        fondo.add(imagemenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 408, -1));

        imagemenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagenmenu(2).png"))); // NOI18N
        fondo.add(imagemenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 100, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOpcion1ActionPerformed
       Balance_general mostrarBalance = new Balance_general();
       mostrarBalance.setVisible(true);
       dispose();
    }//GEN-LAST:event_BotonOpcion1ActionPerformed

    private void BotonOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOpcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonOpcion2ActionPerformed

    private void BotonOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOpcion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonOpcion3ActionPerformed

    private void BotonOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOpcion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonOpcion4ActionPerformed

    private void BotonOpcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOpcion5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonOpcion5ActionPerformed

    private void BotonOpcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOpcion6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonOpcion6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonOpcion1;
    private javax.swing.JButton BotonOpcion2;
    private javax.swing.JButton BotonOpcion3;
    private javax.swing.JButton BotonOpcion4;
    private javax.swing.JButton BotonOpcion5;
    private javax.swing.JButton BotonOpcion6;
    private javax.swing.JLabel bienvenidoTXT;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel imagemenu1;
    private javax.swing.JLabel imagemenu2;
    private javax.swing.JLabel imagemenu3;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel preguntaTXT;
    private javax.swing.JLabel usuarioTXT;
    // End of variables declaration//GEN-END:variables
}
